Repository QoboLtd/project-template-cakephp, pull requests merged in 2019-07, with the labels that each got.

#807 Refactoring Search & JS project architecture (task #11872)
  .editorconfig
  .travis.yml
  README.md
  jest.config.js
  package-lock.json
  package.json
  resources/.babelrc
  resources/.eslintrc.js
  resources/build/utils.js
  resources/build/webpack.base.conf.js
  resources/build/webpack.dev.conf.js
  resources/build/webpack.hot.conf.js
  resources/build/webpack.prod.conf.js
  resources/build/webpack.test.conf.js
  resources/dev/Dev.vue
  resources/dev/dev.js
  resources/dev/index.html
  resources/src/ApiService/ApiSearch.js
  resources/src/components/Dashboard/DashboardGrid.vue
  resources/src/components/Dashboard/DashboardMixin.js
  resources/src/components/Dashboard/DashboardWidget.vue
  resources/src/components/Search/ColumnsMover.vue
  resources/src/components/Search/ColumnsSorter.vue
  resources/src/components/Search/Search.vue
  resources/src/components/ui/TableAjax.vue
  resources/src/store/modules/search/index.js
  resources/src/utils/search.js
  resources/test/unit/.eslintrc
  resources/test/unit/fh/Phone.test.js
  resources/test/unit/helpers/Test.vue
  resources/test/unit/helpers/utils.js
  resources/test/unit/index.js
  resources/test/unit/karma.conf.js
  resources/test/unit/specs/RecurrenceInput.spec.js
  resources/test/unit/visual.js
  tests/Frontend/Controller/UsersController/login.test.js
  tests/Frontend/CustomCommand/login.js
Labels: RFC, enhancement

#818 Adding vue-js-modal as generic modal container (task #12241)
  package-lock.json
  package.json
Labels: enhancement

#821 Execute only if batch action is detected (task #12349)
  src/Controller/Component/CsvViewComponent.php
Labels: bug

#823 Move elements and PHPUnit improvements (task #7507)
  src/Controller/ScheduledJobLogsController.php
  src/Template/Element/Module/Associated/tabs-content.ctp
  src/Template/Element/Module/Embedded/fields.ctp
  src/Template/Element/Module/Embedded/lookup.ctp
  src/Template/Element/Module/Embedded/modals.ctp
  src/Template/Element/Module/Field/input.ctp
  src/Template/Element/Module/Field/value.ctp
  src/Template/Element/Module/Form/fields.ctp
  src/Template/Element/Module/Form/fields_embedded.ctp
  src/Template/Element/Module/Form/fields_panel.ctp
  src/Template/Element/Module/post.ctp
  src/Template/Element/Module/view.ctp
  src/Template/ScheduledJobLogs/view.ctp
  tests/bootstrap.php
Labels: enhancement
